### ISSUE TITLE
Dodać wyświetlanie koordynatów

### ISSUE THREAD

**Issue by JumiDeluxe** [Xelonidas/Projekt-PWI-Szachy#1]
Przy wyświetlanej szachownicy dodać ASCII arty z oznaczeniem koordynatów 1-8, A-H
Propozycja sposobu wyświetlania koordynatów:

![koordynaty_podglad](https://user-images.githubusercontent.com/47438768/104365200-fe0ff700-5517-11eb-9d79-87a8800aadcf.png)

**Comment by wojpok** [comment]
Funkcjonalność dodana
